services:
  - type: web
    name: realtor-rocket-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm run start:server
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: rr-postgres
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: REFRESH_TOKEN_SECRET
        generateValue: true
      - key: ACCESS_TOKEN_EXPIRES_IN
        value: 15m
      - key: REFRESH_TOKEN_EXPIRES_IN
        value: 7d
      - key: VITE_PUBLIC_URL
        value: https://rentara-new.vercel.app
    healthCheckPath: /
    autoDeploy: true 